language: php
php:
  - 5.3
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  # Install bats CLI testing.
  - sudo apt-get install -qq bats
  # Update composer to the latest version.
  - composer self-update
install:
  # Refresh environment variables.
  - phpenv rehash
  # Run installation of all dependencies unsing composer.
  - composer install
before_script:
  # Export phpunit path.
  - export PATH=$PATH:~/.composer/vendor/bin/
script:
  # Run environment tests.
  - bats tests/bats
  - phpunit
